# Generated by Django 4.0.3 on 2022-06-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='teg_recipes', to='foodgram.tag', verbose_name='Тэги'),
        ),
    ]
