# Generated by Django 4.0.3 on 2022-06-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='user_not_subscribe_himself',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='is_subscribed',
            new_name='subscribed_to',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscribed_to'), name='user_not_subscribe_himself'),
        ),
    ]
