# Generated by Django 4.0.3 on 2022-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ing_recipes', through='foodgram.RecipeIngredient', to='foodgram.ingredient'),
        ),
    ]
