# Generated by Django 4.0.3 on 2022-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_alter_subscription_options_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags_recipe', to='foodgram.tag', verbose_name='Тэги'),
        ),
    ]
