# Generated by Django 4.0.3 on 2022-06-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0009_alter_recipe_tags_purchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
    ]
